# Default override when running locally: binds to 127.0.0.1:8080 or another port specified in an env-file.

# When running behind a Docker reverse proxy specify only COMPOSE_FILE=docker-compose.yml to disable this port binding.

# When you want Tailormap to listen on all interfaces, do not set COMPOSE_FILE or keep docker-compose.override.yml in there and
# specify SERVER_ADDRESS=0.0.0.0 in the env-file.

services:
  tailormap:
    ports:
      - ${SERVER_ADDRESS:-127.0.0.1}:${LOCALHOST_PORT:-8080}:8080
  qgisserver:
    ports:
      - ${SERVER_ADDRESS:-127.0.0.1}:${LOCALHOST_PORT:-8081}:80
  postgis:
    ports:
      - ${SERVER_ADDRESS:-127.0.0.1}:${LOCALHOST_PORT:-5432}:5433
